name: currency_rates
description: A sample Flutter application illustrating sealed classes usage.
version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  equatable: ^1.1.1
  freezed_annotation: ^0.7.1
  flutter_bloc: ^4.0.0
  get_it: ^4.0.2
  http: ^0.12.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.10.0
  freezed: ^0.10.9
  lint: ^1.2.0
flutter:
  uses-material-design: true
  assets:
    - assets/images/
